### ISSUE TITLE
Consider updating license to Creative Commons 0

### ISSUE THREAD

**Issue by cablej** [disclose/dioterms#2]
The current disclose.io license is Creative Commons Attribution 4.0 International, which states that users must provide attribution to disclose.io, including a link to the terms. Given that most terms using disclose.io do not link back to the terms, and that disclose.io should be as simple to use as possible, I would suggest updating the license to [Creative Commons 0](https://creativecommons.org/share-your-work/public-domain/cc0/) which reserves no rights and does not have attribution requirements. Of course, this does not stop anyone from citing the terms if they wish, but takes away the requirement to do so.

**Comment by yesnet0** [comment]
Resolved here: https://github.com/disclose/dioterms/pull/8
